language: ruby
rvm:
  - 2.3.4
services:
  - postgresql
before_script:
  - psql -c 'create database palagend;' -U postgres
  - psql -c "create user palagend superuser password 'dddddddd';" -U postgres
  - psql -c 'alter database palagend owner to palagend;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: HtnMLlRNQrscsWRu/GzRVRFMzLSCH6q44JtZRYNS0BcBhHkq+0LwnM9M/xnXOf3s0iBFqWQz5U2zc/fe2w6qegfQgcpY4a+xiby1effbfOxaFF9DMH2DrPpoxtA25/DxV4eLYI5beo8yb1//Ehh/6mGrnn0jJ/1JWTDNh7LqHIoEFLz9FmutUdr+4gjizVtDsu/swvokP+oFzfAXf1Q5EiuZWj0d7/Tb3cV0O6uWAPPec0qM9afafDuqRTeEFj5ipmL35oEgSUOyOwlJAHghpzW081J86aEu87iX8VX3+nrPd/T/0vZpu+EtBlEu274KGcGCqll1KQMRU8P3Cn6SfxQeYzxURV45CAOv6lpw0uMeJwelL37+3Jee4Csz+NLxGtwQCoZ9dVA65H+WyVDbE990m6YX/lbetm84FnFCDd/nH7n0nrSTEfF4Q2dbMPYUWU4YbxgmE7Jqp9C8GC1lViI19jCX10S9CF3OkGcbwHE4QG+zoZz3Vo13YTexSfh7Yce+6KuRhqwhO3AokkJsag1NBGkoaub0y+AybsrXDYLU3+Q7f2IqZWBnMJQ7IrfcBg+yg9bOfELx446qQk/zWoLngJJ9HYjB+LJvzi5V+PayOzGeJUZyKmJNbcNqyUNCu4m3mCMA9EhP5XiCjKREcTMg4y3v7jSaa+h3EwlcngY=
  app: faixberg
  on:
    repo: palagend/blog
